version: '3.8'
services:
  db:
    image: akiunlocks/postgres-takehome:latest
    environment: &db_conf
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret-password
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      retries: 5
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *db_conf
    ports:
      - '5000:5000'
